# -*- coding: utf-8 -*-
"""Database 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n2s4BYG3n_Jg3OeuaZ_FzWIeCvmYU47d
"""

import sqlite3

conn = sqlite3.connect("course.db")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS course_fees (
    subject TEXT,
    analytics TEXT,
    hostel TEXT,
    food_months INTEGER,
    transport TEXT,
    total_fee INTEGER
)
""")
conn.commit()

base_fee = 200000
total = base_fee

subject = input("Enter Subject (HR/Finance/Marketing/DS): ")
analytics = input("Analytics (y/n): ")
hostel = input("Hostel (y/n): ")
food_months = int(input("Food months: "))
transport = input("Transport (semester/annual): ")

if analytics == "Y" and subject != "DS":
    total = total + 20000
if hostel == "Y":
    total = total + 200000
total = total + food_months * 2000
if transport == "semester":
    total = total + 13000
else:
    total = total + 26000

print("\n------ COURSE FEE RECEIPT ------")
print("Subject      :", subject)
print("Analytics    :", analytics)
print("Hostel       :", hostel)
print("Food Months  :", food_months)
print("Transport    :", transport)
print("Total Fees   : ₹", total)
print("--------------------------------")

print("\nSaved Data in Database:")
cursor.execute("SELECT * FROM course_fees")
for row in cursor.fetchall():
    print(row)

conn.close()

